id: A36DD4602
base_file: f421C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:51:54.352029
  last_modified_at: 2022-05-30 20:51:54.352032
